services:
  postgres_db:
    image: postgres:14-alpine
    container_name: auth_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/auth-service/db_init/init.sql:/docker-entrypoint-initdb.d/10-auth.sql
      - ./services/todo-service/db_init/init.sql:/docker-entrypoint-initdb.d/20-todo.sql

  auth-service:
    build:
      context: services/auth-service
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy

  todo-service:
    build:
      context: services/todo-service
      dockerfile: Dockerfile
    container_name: todo_service
    ports:
      - "${TODO_SERVICE_PORT}:${TODO_SERVICE_PORT}"
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  postgres_data:
